#!/usr/bin/env python3
"""Generate/update data/audio_clips_manifest.json for PhraseSplicingTTS.

Enumerates every FIXED (variable-free) response string the system can
produce -- the knowledge-base topics (greeting, consent_prompt,
human_handoff), the consent-decline acknowledgement, and the three
no-data-found fallbacks -- across all three languages, and maps each to an
expected clip file path under data/audio_clips/<lang>/<source_id>.wav.

Run this after adding/changing any fixed template in data/knowledge_base.json
or src/taura/response_generator.py / orchestrator.py, so the manifest stays
in sync with what PhraseSplicingTTS can actually look up. It's safe to run
repeatedly -- existing "recorded" entries are left alone; only the set of
expected strings/paths is refreshed.

Usage:
    PYTHONPATH=src python scripts/generate_clip_manifest.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT_DIR / "src"))

from taura.orchestrator import CONSENT_DECLINE_MESSAGES  # noqa: E402
from taura.rag_retriever import RagRetriever  # noqa: E402
from taura.response_generator import TemplateResponseGenerator  # noqa: E402

LANG_CODES = ["sn", "nd", "en"]
LANG_FIELD = {"sn": "message_sn", "nd": "message_nd", "en": "message_en"}


def collect_fixed_strings() -> dict[str, dict[str, tuple[str, str]]]:
    """Returns {source_id: {lang: (text, relative_clip_path)}}."""
    retriever = RagRetriever()
    responder = TemplateResponseGenerator()
    entries: dict[str, dict[str, tuple[str, str]]] = {}

    # Knowledge-base topics: greeting, consent_prompt, human_handoff.
    for record in retriever.knowledge:
        source_id = record["id"]
        entries[source_id] = {}
        for lang in LANG_CODES:
            text = record.get(LANG_FIELD[lang], record.get("message_en", ""))
            clip_path = f"audio_clips/{lang}/{source_id}.wav"
            entries[source_id][lang] = (text, clip_path)

    # Consent-decline acknowledgement (orchestrator.py constant, not a
    # knowledge_base.json record -- see orchestrator.py's comment on why).
    source_id = "CONSENT-DECLINE-001"
    entries[source_id] = {}
    for lang in LANG_CODES:
        text = CONSENT_DECLINE_MESSAGES.get(lang, CONSENT_DECLINE_MESSAGES["en"])
        entries[source_id][lang] = (text, f"audio_clips/{lang}/{source_id}.wav")

    # No-data-found fallback (response_generator.py).
    source_id = "NO-DATA-FOUND-001"
    entries[source_id] = {}
    for lang in LANG_CODES:
        text = responder.no_data_found(lang)
        entries[source_id][lang] = (text, f"audio_clips/{lang}/{source_id}.wav")

    return entries


def build_manifest(entries: dict[str, dict[str, tuple[str, str]]], existing: dict) -> dict:
    clips: dict[str, dict[str, dict]] = {lang: {} for lang in LANG_CODES}
    counts = {"recorded": 0, "missing": 0}

    for source_id, by_lang in entries.items():
        for lang, (text, clip_path) in by_lang.items():
            abs_path = ROOT_DIR / "data" / clip_path
            status = "recorded" if abs_path.exists() else "missing"
            counts[status] += 1
            clips[lang][text] = {
                "file": clip_path,
                "source_id": source_id,
                "status": status,
            }

    return {
        "_note": (
            "Generated by scripts/generate_clip_manifest.py. 'status':'missing' "
            "means the fixed response text is registered but no recording "
            "exists yet at 'file' -- see data/audio_clips/README.md. "
            "PhraseSplicingTTS falls back to text-only output for any text "
            "not in this manifest (all price/climate/financial responses) "
            "or any 'missing' entry -- see src/taura/tts.py."
        ),
        "_counts": counts,
        "clips": clips,
    }


def main() -> None:
    manifest_path = ROOT_DIR / "data" / "audio_clips_manifest.json"
    existing = {}
    if manifest_path.exists():
        with open(manifest_path, "r", encoding="utf-8") as f:
            existing = json.load(f)

    entries = collect_fixed_strings()
    manifest = build_manifest(entries, existing)

    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)
        f.write("\n")

    counts = manifest["_counts"]
    print(f"Wrote {manifest_path}")
    print(f"  recorded: {counts['recorded']}, missing: {counts['missing']}")
    if counts["missing"]:
        print(
            "  Record the missing clips per data/audio_clips/README.md, then "
            "re-run this script to update their status."
        )


if __name__ == "__main__":
    main()
