"""Central configuration for the Taura AI prototype.

All values are overridable via environment variables (see .env.example).
Nothing here requires secrets to run the offline demo.
"""
from __future__ import annotations

import os
from pathlib import Path

# Repository root (two levels up from this file: src/taura/config.py -> repo root)
ROOT_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = Path(os.getenv("TAURA_DATA_DIR", ROOT_DIR / "data"))
LOG_DIR = Path(os.getenv("TAURA_LOG_DIR", ROOT_DIR / "logs"))
LOG_DIR.mkdir(parents=True, exist_ok=True)

AUDIT_LOG_PATH = LOG_DIR / "audit.log"

# Default response language when the user's language cannot be confidently
# detected. One of: "sn" (Shona), "nd" (Ndebele), "en" (English fallback).
DEFAULT_LANGUAGE = os.getenv("TAURA_DEFAULT_LANGUAGE", "sn")

# Response generation backend: "template" (default, offline, deterministic)
# or "llm" (requires TAURA_LLM_PROVIDER + credentials; see response_generator.py).
RESPONSE_BACKEND = os.getenv("TAURA_RESPONSE_BACKEND", "template")

# Feature flag: require explicit consent before the first substantive answer
# in a session, matching the Data Protection Act [Chapter 12:07] handling
# described in the written proposal.
REQUIRE_CONSENT = os.getenv("TAURA_REQUIRE_CONSENT", "true").lower() == "true"

# --- ASR backend selection ---------------------------------------------
# "passthrough" (default, offline): treats input as already-transcribed text;
#     used by the CLI/WhatsApp/USSD simulators and the web demo.
# "mms": Meta Massively Multilingual Speech (facebook/mms-1b-all), loaded via
#     transformers with a language adapter. Requires requirements-asr.txt and
#     network access to download the checkpoint on first use.
# "whisper_finetuned": a Whisper checkpoint fine-tuned on the consented
#     pilot-site Shona/Ndebele voice corpus, loaded from TAURA_ASR_MODEL_PATH.
ASR_BACKEND = os.getenv("TAURA_ASR_BACKEND", "passthrough")

# ISO 639-3 language code for the MMS language adapter. "sna" = Shona,
# "nde" = (North) Ndebele -- the variety spoken in Zimbabwe, as distinct from
# "nbl" (South Ndebele, South Africa). Verify against Meta's published MMS
# language table before relying on this in production; language coverage is
# occasionally revised between checkpoint releases.
ASR_MMS_LANGUAGE = os.getenv("TAURA_ASR_MMS_LANGUAGE", "sna")
ASR_MMS_MODEL_ID = os.getenv("TAURA_ASR_MMS_MODEL_ID", "facebook/mms-1b-all")

# Local directory (or HF Hub repo id) of a Whisper checkpoint fine-tuned on
# the pilot-site voice corpus. Only used when ASR_BACKEND=whisper_finetuned.
ASR_WHISPER_MODEL_PATH = os.getenv("TAURA_ASR_WHISPER_MODEL_PATH", "")

# Local directory (or HF Hub repo id) of a wav2vec2-XLSR checkpoint
# fine-tuned on the pilot-site voice corpus (Apache-2.0 base, see
# docs/OSI_LICENSED_ALTERNATIVES.md). Only used when
# ASR_BACKEND=xlsr_finetuned.
ASR_XLSR_MODEL_PATH = os.getenv("TAURA_ASR_XLSR_MODEL_PATH", "")

# --- TTS backend selection ---------------------------------------------
# "passthrough" (default, offline): returns text unchanged, no audio.
# "mms": Meta MMS-TTS (facebook/mms-tts-<lang>), one checkpoint per language,
#     loaded via transformers. Requires requirements-asr.txt and network
#     access to download the checkpoint on first use.
# "phrase_splicing": pre-recorded audio clips for FIXED (variable-free)
#     response templates only (greeting, consent prompt, human handoff,
#     no-data-found) -- the "top intents" mitigation named in the written
#     proposal, Section 4.5. Falls back to passthrough (text only, no audio)
#     for any response text not found in the clip manifest, e.g. a price
#     response with a variable dollar figure -- see data/audio_clips/README.md.
TTS_BACKEND = os.getenv("TAURA_TTS_BACKEND", "passthrough")

TTS_MMS_MODEL_ID_TEMPLATE = os.getenv("TAURA_TTS_MMS_MODEL_ID_TEMPLATE", "facebook/mms-tts-{lang}")

# Local directory or private HF Hub repo id of a self-trained VITS checkpoint
# (MIT/Apache-2.0-clean training path -- see docs/OSI_LICENSED_ALTERNATIVES.md),
# used in place of Meta's NC-licensed facebook/mms-tts-<lang> checkpoints.
# Only used when TTS_BACKEND=custom_vits. Unlike TTS_MMS_MODEL_ID_TEMPLATE,
# this is a single id, not a per-language template, since a self-trained
# checkpoint is typically one model per language you explicitly point to.
TTS_CUSTOM_VITS_MODEL_ID = os.getenv("TAURA_TTS_CUSTOM_VITS_MODEL_ID", "")

# Path to the phrase-splicing clip manifest generated by
# scripts/generate_clip_manifest.py. Maps exact response text -> audio file.
TTS_CLIP_MANIFEST_PATH = os.getenv(
    "TAURA_TTS_CLIP_MANIFEST_PATH", str(DATA_DIR / "audio_clips_manifest.json")
)
